kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

steps:
  - name: build
    image: swift:latest
    commands:
      - cd Sources/HelloLibrary
      - swift build

  - name: tests_Model
    image: swift:latest
    commands:
      - cd Sources/HelloLibrary
      - swift test
    depends_on: [build]
      